### PR TITLE
tests, optimizations, documentation fixes

### PR DESCRIPTION
**Pull request by lue-bird**
- adds fuzz tests for every operation
- adds benchmark for almost every operation, tested with normal elm compilation and `elm-optimize-level-2`: see the `specific-benchmark/` folder which includes pdfs of both compilation modes
- documentation fixes, like sometimes calling ropes lists or using lists instead of ropes in the examples
- switches to the best\* implementations

\* most are decisive between browsers and compilation mode. I chose the fastest option with `elm-optimize-level-2` only when it wasn't significantly slower on normal compilation mode.

Pick the parts that you like :)

Separate note: `filter`, `filterMap`, `concat`, `concatMap` do/should not keep (nested) empty ropes around but `isEmpty` is somewhat costly since it recursively walks to every sub-tree. I tried representing its empty state uniquely in [the branch `explicit-emptiness`](https://github.com/lue-bird/elm-rope/tree/explicit-emptiness)

### CODE REVIEW

**Comment by miniBill** [comment]
... why does it say I close it? o.O

**Comment by lue-bird** [comment]
> I see you "reverted" that exposing in https://github.com/miniBill/elm-rope/commit/afef9259e1d6cdae04fb716fe50575bedfb8262c, but then that means having two copies of the same file, which smells to me. Should probably go for the Internal path

I would love this! But elm considered switching from `type` to `type alias = Internal` to be a breaking change. If that's not an issue for you, let's do it!

**Comment by miniBill** [comment]
Yeah, not an issue, especially because it's not actually breaking (and, as you said, the number of users is probably really small)

**Comment by miniBill** [comment]
Ok, pushed the change to `main`

**Pull request closed without merging**
